### ISSUE TITLE
Content of column "location" shows ', ,' - why is there no data maintained?

### ISSUE THREAD

**Issue by 74cmonty** [dsoares/Roundcube-Plugin-Lastlogin#14]
Content of column "location" shows two commas inserted?
![2016-07-26_13-39-07](https://cloud.githubusercontent.com/assets/12523591/17177155/57d9f276-5410-11e6-84c6-911852941211.png)
Why is there no real location data maintained?

**Comment by dsoares** [comment]
Maybe because you didn't configure your system's GeoIP C library properly. Check the [GeoIP PHP requirements](http://php.net/manual/en/book.geoip.php) and install the free [GeoLite2 Free Downloadable Databases](http://dev.maxmind.com/geoip/geoip2/geolite2/) from MaxMind.

You may test from the command-line with:
`$ geoiplookup 155.56.40.65`

If this command shows the correct information and the plugin lastlogin still returns an empty location, then please reopen this issue.

**Comment by 74cmonty** [comment]
confirmed
